automator:
  stage: deploy
  image: node:$NODEJS_VERSION
  allow_failure: true
  parallel: 4
  only:
    - master
  before_script:
    - mkdir -p ~/.ssh
    # 1) Setup GitLab access:
    - echo "$AUTOMATOR_SSH" | tr -d '\r' > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - ssh-keyscan -H 'gitlab.skypicker.com' >> ~/.ssh/known_hosts
    - ssh -T git@gitlab.skypicker.com
    # 2) Setup GitHub access (using RSA instead so we don't have to deal with SSH config):
    - echo "$AUTOMATOR_GITHUB_SSH" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H 'github.com' >> ~/.ssh/known_hosts
  script:
    - yarn install --offline --frozen-lockfile
    - yarn monorepo-babel-node src/core/automator/src/index.js
